### ISSUE TITLE
MATPostBuildTrigger.cs  problem with Facebook_SDK_for_unity

### ISSUE THREAD

**Issue by neowizz** [MobileAppTracking/unity-plugin#3]
Problem:
   MATPostBuildTrigger.cs has the following code

line 191 : fCurrentXcodeProjFile.Write("\t\t\t\tFRAMEWORK_SEARCH_PATHS = (\n\t\t\t\t\t\"$(inherited)\",\n\t\t\t\t\t\"\\\"$(SRCROOT)/" + "." + "\\\"\",\n\t\t\t\t);\n");

  which adds the following code after "OTHER_CFLAGS" block in the "project.pbxproj" file
				FRAMEWORK_SEARCH_PATHS = (
					"$(inherited)",
					"\"$(SRCROOT)/.\"",
				);

  I think the code in 191 line is unnecesssary because unmodified project.pbxproj already has the "FRAMEWORK_SEARCH_PATHS" block. 

And the added "FRAMEWORK_SEARCH_PATHS" blocks in the project.pbxproj causes exception Error during the post build process if you are using "Facebook_SDK_for_Unity 6.0" or above version.

The exception happens
"Assets\Facebook\Editor\iOS\third_party\XCodeEditor-for-Unity\PBXParser.cs" which is used by "Assets\Facebook\Editor\FacebookPostprocess.cs"

line 182:                    case DICTIONARY_ASSIGN_TOKEN:
line 183:                        valueObject = ParseValue();
line 184:                        dictionary.Add( keyString, valueObject ); // exception raises here
line 185:                        break;

How to Solve:
- modify the PBXParser.cs like this

line 182:                    case DICTIONARY_ASSIGN_TOKEN:
line 183:                        valueObject = ParseValue();
line 184:                        if (dictionary.ContainsKey(keyString)) 
line 185:                            dictionary[keyString] = valueObject;
line 186:                         else
line 187:                            dictionary.Add( keyString, valueObject );
line 188:                        break;

- or just comment line 191 of MATPostBuildTrigger.cs

line 191 : //fCurrentXcodeProjFile.Write("\t\t\t\tFRAMEWORK_SEARCH_PATHS = (\n\t\t\t\t\t\"$(inherited)\",\n\t\t\t\t\t\"\\\"$(SRCROOT)/" + "." + "\\\"\",\n\t\t\t\t);\n");

FYI, I'm using the following tools
•Unify 4.6.5f1 (on Windows and MAC)
•XCode 6.3.1 (6D1002)
•Facebook SDK for Unity 6.0 or above (v6.2.2 - April 14, 2015, FacebookSDK-150414.unitypackage)
•MAT plugin 3.9.1 (using sample/Assets files ; Updated for iOS 3.9.1)

**Comment by neowizz** [comment]
FYI, I'm using the following tools

- Unify 4.6.5f1 (on Windows and MAC)
- XCode 6.3.1 (6D1002)

- Facebook SDK for Unity 6.0 or above (v6.2.2 - April 14, 2015, FacebookSDK-150414.unitypackage)
- MAT plugin 3.9.1 (using sample/Assets files ; Updated for iOS 3.9.1)

**Comment by harshal-hasoffers** [comment]
Thanks for pointing this out. We fixed it by removing line 191 related to FRAMEWORK_SEARCH_PATHS.
