### ISSUE TITLE
Show Unity plugin mappings to native SDKs

### ISSUE THREAD

**Issue by mreeves1** [MobileAppTracking/unity-plugin#4]
Could a text file be added to more explicitly show how each version of this unity-plugin maps to the native SDKs for iOS, Android, etc.? 

For instance unity-plugin 3.9.3 appears to map to Android plugin 3.9.1 and iOS plugin 3.9.1 based on the names of the files imported to the Assets Android and iOS folders. 

Also is there a timeline for when the Unity plugin will be more up to date with the native sdks? Thanks!

**Comment by harshal-hasoffers** [comment]
- We plan to update the Unity plugin to the latest Android, iOS SDK versions later this week.
- The README.md file will also mention the version numbers of the included native SDKs.

**Comment by christian-putzke** [comment]
How is the Update going? I would like to get the newest version too ;)

**Comment by harshal-hasoffers** [comment]
@christian-putzke Attached here is the latest plugin which should work for Android and iOS (to unarchive, please change extension to .zip). The general plugin release will follow after further testing on Windows/Metro platforms.
![mobileapptracker_zip](https://cloud.githubusercontent.com/assets/2146296/10181087/8974154a-66c8-11e5-9b94-b215fe2f831d.jpg)

**Comment by john-gu** [comment]
v3.10.0 has been released with the latest SDKs
