### ISSUE TITLE
Wrong package_name?

### ISSUE THREAD

**Issue by boerjesieling** [MobileAppTracking/unity-plugin#8]
Hi,
After integrating the SDK we were not able to find any event in the Logs. When debugging the URLs, I saw that the package_name parameter was something like com.hasoffers.unitypackage (bundle_id had a correct value). Setting the package_name property with the Tune API in the code seemed to resolve this issue. Maybe this should be explained in here https://developers.tune.com/sdk/unity-quick-start  (or automaticly set to the same value as the bundle_id)

**Comment by boerjesieling** [comment]
Hmm.. ok, maybe this was related with the MyAppDelegate which was removed in the last version.

**Comment by john-gu** [comment]
Hi @boerjesieling, I believe you are correct. The custom AppDelegate was mistakenly added to the `unitypackage` file and was setting package name to our sample app's. Without it, it should detect yours correctly.
